### ISSUE TITLE
possible?

### ISSUE THREAD

**Issue by devcrono** [bucanero/apollo-ps4#119]
@bucanero 
I noticed that in the new version you included the possibility of making a download, via ftp, ftps, http and https, however they epanas take a direct download, and if instead it is a single download, it allows accessing a site, or drive, or in the , or webdav, or google shared drive?

With that, you could download everything through the link, just click on the main link and the entire list of folders available on the link would appear.

this app

https://github.com/cy33hc/ps4-ezremote-client

allows you to download all forms of sharing available, however its visual, and as if it were a very "rustic" but fully functional "ftp" directory, what I mean is that if possible, at a glance like this I could add to function to add a directory, or a personal drive to download whenever you open the link, or even add a new menu in the main grid after you add the link, you could make a mini PSN if you have the games, you know a webdav for example

**Comment by bucanero** [comment]
Apollo is focused on handling save-game data, and the network tools are there to transfer saves. You can still use them for emergencies, but I think a specific app for file management is a better choice.

I think that it's a kind of improvement / feature that could be added to the `ps4-ezremote-client` app, since it already has the file management and code to connect using many protocols like ftp, http, webdav, smb, nfs, ++.
