### ISSUE TITLE
Saves and Codes update

### ISSUE THREAD

**Issue by RllsR** [bucanero/apollo-ps4#13]
Hi. I've got a problem with my app, or so I think.

How do I update the app contents?

When I try to check the "Online DB", I have the "No save-games found" popup on my screen.
Also, when trying to apply cheats to save games, a few of the ones listed here in apollo-ps4/appdata/ doesn't show in my app.

I tried the Settings/Update Application Data but nothing happens.

**Comment by bucanero** [comment]
> Hi. I've got a problem with my app, or so I think.
> 
> How do I update the app contents?

You can update the cheat-code files by adding or editing the files on your PS4 drive. The files are stored in this folder: `/data/apollo/data`.

> 
> When I try to check the "Online DB", I have the "No save-games found" popup on my screen. 

Yes, there's currently an issue with the URL of the online DB. (#14) It will be fixed in the next version  

> Also, when trying to apply cheats to save games, a few of the ones listed here in apollo-ps4/appdata/ doesn't show in my app.

Keep in mind that Apollo doesn't auto-update or sync with the files on the GitHub repository. You can check in your `/data/apollo/data` folder if you have the file or not. Also the codes will only show up if your savegame has the same title-id, CUSAxxxxx. If the title-id is different, like a different region of a game, cheats won't show up.

> 
> I tried the Settings/Update Application Data but nothing happens.

Yes, this would be the way to update the cheat code files, but due to this URL issue right now Apollo can't reach the server and download the update pack. It will be fixed with the new version too.

**Comment by bucanero** [comment]
Fixed in a1594a8
