### ISSUE TITLE
0.8: sluggishness

### ISSUE THREAD

**Issue by subworx** [bucanero/apollo-ps4#19]
Hi,
thank you for this awesome tool.
Looking into whipping up some save editing stuff for Persona 5 Royal as the offsets differ from regular Persona 5 :)

PS4 Pro 9.00, GoldHen v2b2 and WebRTE (karo218) loaded.
Using Apollo 0.8.0, "dirty install" over 0.7.0.

The good: On a 4k TV, text is way bigger now. The controls also seem to work better, not jumping zero or 2-3 entries when pressing up or down once on the d-pad.

The not so good: When browsing HDD saves at least, all animations feel sluggish. When selecting "Info" (Triangle) about a savegame, the panel pretty slowly slides in, in 0.7.0 it just popped up. Choosing e.g. Export to Zip, the target location panel again slides in very slowly. When returning to the list with Circle, the tool is stuck at the top entry ("Bulk Save Management") before actually jumping to the previously selected entry.

Hope this is understandable.
Again, thank you.

Best regards,
sub

**Comment by bucanero** [comment]
Just in case: you can disable all the animations by going to the `Settings` menu and disabling the animation option. This will give you a similar UI behavior as it was in previous versions.

Personally I'm usually working with animations disabled as I just need to test things and don't want to waste time with the eye candy, but I enabled the screen transitions because it was part of the PS3 version.

**Comment by subworx** [comment]
Disabling animations did the trick. Thank you :)
