### ISSUE TITLE
Extremelly slow performance

### ISSUE THREAD

**Issue by zaykho** [bucanero/apollo-ps4#2]
PS4 Fat 5.05 - IV0000-APOL00004_00-APOLLO0000000PS4.pkg

I tested the first public beta of Apollo Save Tool for PS4, and I get very very bad performance while using it, all the navigation in the menu are very slow, the joypad feel unresponsive and it require to press many time the same button before it actually move on screen, is this normal ?

I precise, I never got that issue anywhere else.

EDIT: Seems one of the core is at 100%, could this be the reason ?
![Apollo Save Tool_20211225213925](https://user-images.githubusercontent.com/6943022/147393233-cd157281-c6df-4cc0-a774-097cc3eca5b0.png)

**Comment by bucanero** [comment]
Yes, the beta had performance issues. Currently Open Orbis SDK doesn't have hardware accelerated graphics, so the whole UI is drawn using software rendering (slow and CPU-intensive).

As a work-around for v0.6.0 I decided to render a smaller screen, because full-HD (1920x1080) on software render has this huge performance impact.

There are some libraries in development that should bring OpenGL to OpenOrbis, so once those libraries are ready I can upgrade Apollo's interface with proper GPU graphics.

**Comment by bucanero** [comment]
Fixed in [0.7.0](https://github.com/bucanero/apollo-ps4/releases/tag/v0.7.0)
