### ISSUE TITLE
Trophies, trophies, trophies

### ISSUE THREAD

**Issue by arfghie** [bucanero/apollo-ps4#36]
when i try to get into the trophies section, the console give an error and the app crash. This is 6.72.
Anyways i wanted to request a helper from the trophie section, that is to show the NPWR code for the CUSA involved.
At the moment i havent seen any app that help on that showing that NPWR trophy code...

thx in advance

**Comment by bucanero** [comment]
you need to provide additional details and files to review this issue:

- open Apollo, go to `Settings`, and click on the option to "Enable debug logs"
- now try to open the `Trophies` menu. After the app crashes, copy the log file from `/data/apollo/apollo.log`
- upload the `apollo.log` file to this issue
- also upload the `trophy_local.db` file from your ps4 account.

For more info see #28

**Comment by arfgh** [comment]
Ok  bucanero, here you have the log, just enabled it and then wanted to get into trophies section, and then, appl error happens. Maybe you know reason of this.... i hope.

[2022-03-17 15:31:39] ----- File (/data/apollo/apollo.log) debug logger initialized -----
[2022-03-17 15:31:47] Saving Settings...
[2022-03-17 15:31:54] Opening 'file:memdb?ptr=0x200E60020&sz=413696&freeonclose=1'...
[2022-03-17 15:31:54] [NPWR14797_00] F(640) name 'Genesis Alpha One'
[2022-03-17 15:31:54] [NPWR14510_00] F(640) name 'EVERSPACE'
[2022-03-17 15:31:54] [NPWR14626_00] F(640) name 'Conan Exiles'
[2022-03-17 15:31:54] [NPWR13348_00] F(640) name 'The Last of Us™ Parte II'
[2022-03-17 15:31:54] [NPWR06616_00] F(640) name 'The Order: 1886'
[2022-03-17 15:31:54] [NPWR05777_00] F(640) name 'Sniper Elite 3'
[2022-03-17 15:31:54] [NPWR08997_00] F(640) name 'Fallout 4'
[2022-03-17 15:31:54] [NPWR06418_00] F(640) name 'The Last of Us™ Remasterizado'
[2022-03-17 15:31:54] [NPWR16437_00] F(640) name 'Flashback'
[2022-03-17 15:31:54] [NPWR05659_00] F(640) name 'Dying Light'

**Comment by bucanero** [comment]
> Ok bucanero, here you have the log, just enabled it and then wanted to get into trophies section, and then, appl error happens. Maybe you know reason of this.... i hope.

please can you also upload the tropy_local.db file for this user? you can find it on `/user/home/<USER-ID>/trophy/db/trophy_local.db`

**Comment by arfgh** [comment]
yes, here it is: https://mega.nz/file/fpRSGa6S#hnSWlYB22X7HatrYkebtdeDeZZdV6cCYHMag2a6vnDw
please confirm when you get it...

**Comment by arfgh** [comment]
ok, i may know reason of the app crash. In t he trophy_local.db, in servera table sections i have empty entries with STATUS column set as 1. I have deleted these entried in all the tables that there are entries with status = 1, and then Apollo successfully load the trophy section. But the  problem keeps, because once i get into the trophy menu to see all of them, these entries with status = 1 are regenerated by the system. And by the way, next time i want to get into trophies section of Apollo, again crash.

So is there a way to avoid the system to regenerate these entries with status = 1 ?

**Comment by bucanero** [comment]
> yes, here it is: https://mega.nz/file/fpRSGa6S#hnSWlYB22X7HatrYkebtdeDeZZdV6cCYHMag2a6vnDw please confirm when you get it...

thanks, I've downloaded the database file. I'll review it and try to get rid of this bug

> ok, i may know reason of the app crash. In the trophy_local.db, in serveral table sections i have empty entries with STATUS column set as 1. I have deleted these entried in all the tables that there are entries like these, and then Apollo successfully load the trophy section. But the problem keeps, because once i get into the console trophy menu to see all of them, these entries with status = 1 are regenerated by the system. And by the way, next time i want to get into trophies section of Apollo, again the crash.

oh thanks for this feedback, is really useful and might be the root cause of this bug. Since it's a SQLite database I'm pretty sure I could change the query to skip all these `status=1` entries and avoid the crashes. In that case it won't be necessary to remove those entries or worry about getting regenerated.

I'll check and see if skipping those entries fix the issue.
