### ISSUE TITLE
Can't get Apollo to work correctly.

### ISSUE THREAD

**Issue by godreborn** [bucanero/apollo-ps4#41]
hello, bucanero, my friend, this is the thread I mentioned to you on discord: https://gbatemp.net/threads/ps4-apollo-save-tool-failed.609603/

**Comment by bucanero** [comment]
hi, I checked the message. I think those saves are lost now, because the user already formatted the PS4. If saves were not copied to USB, now there's nothing we can do.

One possible explanation besides faulty/corrupt USB drive, could be that the user didn't had the latest Apollo version (v1.0.1) and used Apollo v1.0.0 that had a bug with bulk save management (#27 ).
It would be a very unfortunate coincidence, but I think it's possible.
