### ISSUE TITLE
Change FW saves

### ISSUE THREAD

**Issue by Amethxst** [bucanero/apollo-ps4#53]
Hi!
I was importing a save to PS4 when I didn't realize the save was from the latest system version
Apollo rightly warned me of the impossibility of copying the file on the console since it comes from a higher FW, I wanted to ask if in the future it was possible to implement an option that selecting the save from the USB, would make you choose the destination FW (and modify it to its lap)

In any case, I take this opportunity to congratulate you on the work you have done ^^

**Comment by leolapi4** [comment]
Yeah, it will be cool to copy the saves between firmware versions. I will now try to copy from 6.72 to 9.00 (maybe only game data, not the save entirely), because I don't want to update 6.72 firmware as it's the latest stable with no USB stick required to HEN enabling and I still want to continue with playing on 9.00 firmware.

**Comment by bucanero** [comment]
For the record, if you export the decrypted save-game to USB using Apollo, you'll be able to import it on any firmware version using Apollo too.

Only the encrypted kind of save-game is restricted to firmware versions and that's why I always recommend to export **decrypted** saves using Apollo instead of the encrypted version that is version-limited.
