### ISSUE TITLE
[Request] Some saves from legit games don't work with fpks

### ISSUE THREAD

**Issue by Scalerize** [bucanero/apollo-ps4#62]
Like the title says, I tried importing my ps4 saves from my ps5 to my jb ps4 from legit games and most of them work on fpks but not all, as some of them show save corrupted when loading the save. Wondering if there's something you can do about it on your end ? maybe a feature on apollo that makes the saves work, I'm told that it may be a keystone issue, a member of the scene said "Just change your save keystone to 0s" Here's a [link](https://www.reddit.com/r/ps4homebrew/comments/8qlfem/you_can_use_legit_saves_with_fpkg_games/?utm_medium=android_app&utm_source=share) that might help you identify what i want and sorry of this seems like a stupid thing to ask :)

**Comment by bucanero** [comment]
the issue is that some `fpkg`s don't respect the original `keystone` from the original game pkg.
So the saves from the original game end up being incompatible with the saves created by the fpkgs.

Why it works with some games? because the fpkg was built properly and kept the original game keystone.

Anyways, Apollo already have the feature to export and import keystone files. You just need to exchange keystones between a save created by the fpkg and the save from the original game.

But the keys must be replaced **before** you try to load the save. Once you tried the load the save with a wrong keystone, the save will be flagged as corrupt and you'll have to delete it.

**Comment by Scalerize** [comment]
Thanks for your response, But i guess what i meant was a button to change the keystone of legit saves to 0's to make it easier as i am aware of the import and export keystone feature.
