### ISSUE TITLE
Dying light 

### ISSUE THREAD

**Issue by Ilkin30** [bucanero/apollo-ps4#78]
hello everyone. i'm trying to download a save for dying light 1 from a flash drive via Apollo. but an error appears: Error! Can't mount encrypted save (incompatible save-game firmware version). I downloaded version 1.00 and 1.35 of the game, with and without dls. and still there is an error. how to fix it? my console version is 5.05. I also tried to download the save for Tsushima and Dark Souls, there is also this error

**Comment by bucanero** [comment]
The problem is that you're trying to import / load an encrypted save that was created with a ps4 on higher firmware.
You're using 5.05 but the encrypted save could have been created with 7.x, 9.x, etc. There's no solution for that.

Only possible options are: get a decrypted save-game (or ask someone on a higher firmware to decrypt it for you). You can also upgrade to 9.0 jailbreak and might be able to load more encrypted saves than on 5.05.

**Note:** You'll get the same notification if you try to load encrypted saves created on higher firmwares.
