### ISSUE TITLE
use cheat

### ISSUE THREAD

**Issue by scanner22** [bucanero/apollo-ps4#81]
Hello. I was using appollo for AC Valhalla and saw there is a list of cheat with item swaper like for save wizard. 

After using this, when I go in game, I have a pop-up saying the save is damaged and I need to choose my HDR setting again. And I don't get my stuff changed. 
Also, I would like to know how to edit/add others cheats to swap item I want.

**Comment by bucanero** [comment]
Most save wizard codes on Apollo are untested and might not work, due to additional security measures, like:
- the save-data has a checksum that needs to be updated to match
- the save-data has custom second layer encryption, so data must be decrypted before applying changes

I assume that AC Valhalla at least has a data checksum to avoid tampering with the files. The original Save wizard tool has the ability to custom decrypt data and regenerate checksums and hashes as needed. Since there's no such information available, Apollo can patch the save but the game will still detect the data corruption.

There's no fix unless someone analyze the AC save-game and crack any checksum or encryption.
